# Generated by Django 4.1.7 on 2023-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
